# Generated by Django 5.0.6 on 2024-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_rename_users_userreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='username',
        ),
        migrations.AlterField(
            model_name='userreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
