# Generated by Django 5.0.6 on 2024-07-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_remove_userreg_password_remove_userreg_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userreg',
        ),
    ]
