# Generated by Django 5.0.6 on 2024-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userreg',
        ),
    ]
