# Generated by Django 5.0.6 on 2024-07-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='usertype',
        ),
    ]
