# Generated by Django 5.0.6 on 2024-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_doctorreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreg',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='user',
        ),
    ]
