# Generated by Django 5.0.6 on 2024-08-03 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_category_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
