# Generated by Django 5.0.6 on 2024-08-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_rename_category_name_category_name_blogs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=25),
        ),
    ]
