# Generated by Django 5.0.6 on 2024-08-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_alter_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctorreg'),
        ),
    ]
