# Generated by Django 5.0.6 on 2024-08-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0016_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctorreg')),
            ],
        ),
    ]
