# Generated by Django 5.0.6 on 2024-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0017_doctoroauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
